# Generated by Django 3.0.1 on 2021-06-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=200)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('year_study', models.CharField(blank=True, max_length=200)),
                ('total_quizzes_given', models.IntegerField(blank=True, default=0)),
                ('average_score', models.IntegerField(blank=True, default=0)),
                ('profile_img', models.ImageField(blank=True, default='aaaaaaa.jpeg', upload_to='photos/%y/%m/')),
            ],
        ),
    ]
