# Generated by Django 3.0.1 on 2021-06-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20210618_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='forum_image',
            field=models.ImageField(blank=True, default='aaaaaaa.jpeg', upload_to='photos/%y/%m/'),
        ),
    ]
