# Generated by Django 3.0.1 on 2021-06-13 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0033_auto_20210613_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 13, 20, 24, 23, 710413)),
        ),
    ]
