# Generated by Django 3.0.1 on 2021-06-18 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0042_auto_20210618_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='private_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_sub_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_alloted',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 18, 19, 21, 19, 928469)),
        ),
    ]
