# Generated by Django 3.0.1 on 2021-06-22 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0043_auto_20210618_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_5',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_6',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_7',
        ),
        migrations.RemoveField(
            model_name='question',
            name='prob_img_3',
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 23, 47, 432610)),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.CharField(default='Both of these', max_length=200),
        ),
    ]
